label_mapping:
  imagenet-a: 0
  imagenet-200: 0
  imagenet-r: 1
  imagenet-c: 0
  imagenet-train: 0
  imagenet-val: 0
  imagenet-sketch: 1
  imagenet-v2: 0
  objectnet-subsample: 0
  DomainNet: 1
  dn-clipart: 1
  dn-infograph: 1
  dn-painting: 1
  dn-quickdraw: 1
  dn-real: 0
  dn-sketch: 1
  laion400m: 0
  laion200m: 0
  laion200m_0: 0
  laion200m_1: 0
  laion200m_2: 0
  laion200m_3: 0
  laion200m_4: 0
  laion200m_5: 0
  laion200m_6: 0
  laion200m_7: 0
  laion200m_8: 0
  laion200m_9: 0
  laion200m_10: 0
  laion200m_11: 0
  laion200m_12: 0
  laion200m_13: 0
  laion200m_14: 0
  laion200m_15: 0
  laion200m_16: 0
  laion200m_17: 0
  laion200m_18: 0
  laion200m_19: 0
  laion1m: 0
  yfcc100m-data: 0
  100K_3: 0
  100K_333: 0
  10K_round1_0: 0
  10K_round1_1: 1
  10K_round1_2: 2
  10K_round1_subsample_0: 0
  10K_round1_subsample_1: 1
  10K_round1_subsample_2: 2
  dn_quickdraw_1k: 1