# # config for train (keys should match config keys)
# # Each of these arguments will be passed to start a job. Several jobs will be created based on possible combinations
# # of values across arguments. Each value is represented by '-'. Template is given below:
#cluster:
#  - mpi
#base_directory:
#  - /is/cluster/fast/pmayilvahanan/clip_ood_part2/results/
#arch:
#  - ViT-B-32-quickgelu__laion400m_e32
#  - ViT-B-16-plus-240__laion400m_e32
#  - ViT-L-14__laion400m_e32
#  - ViT-B-16__laion2b_s34b_b88k
#  - ViT-L-14__laion2b_s32b_b82k
#  - dinov2_vitg14_reg

#pretrained:  # very important
#  - True
#freeze_encoder:
#  - True
#  - False
#batch_size:
#  - 1024
#  - 2048
#dataset:
#  - imagenet-val objectnet-subsample imagenet-v2 imagenet-a imagenet-200 dn-real imagenet-r imagenet-sketch dn-clipart dn-painting dn-sketch dn-infograph
#  - 1.5K_round3_stylistic_v_rest_balanced
#  - 3K_round3_stylistic_v_rest_balanced
#  - 4.5K_round3_stylistic_v_rest_balanced
#  - 6K_round3_stylistic_v_rest_balanced
#  - 2K_round3_natural_v_rest_balanced
#  - 4K_round3_natural_v_rest_balanced
#  - 7K_round3_natural_v_rest_balanced
#  - 9K_round3_natural_v_rest_balanced
#  - 11K_round3_natural_v_rest_balanced
#  - 2.5K_round3_natural_v_rest
#  - 4K_round3_natural_v_rest
#  - 7K_round3_natural_v_rest
#  - 10K_round3_natural_v_rest
#  - 13K_round3_natural_v_rest
#  - 2.5K_round3_stylistic_v_rest
#  - 4K_round3_stylistic_v_rest
#  - 7K_round3_stylistic_v_rest
#  - 10K_round3_stylistic_v_rest
#  - 13K_round3_stylistic_v_rest
cluster:
  - mpi
base_directory:
  - /is/cluster/fast/pmayilvahanan/clip_ood_part2/results/
arch:
  - ViT-g-14__laion2b_s34b_b88k
  - dinov2_vitg14_reg
  - ViT-L-14__laion2b_s32b_b82k
freeze_encoder:
  - False
fourier:
  - False
image_folder:
  - True
batch_size:
  - 160
pretrained:
  - True
num_classes:
  - 2
dataset:
  - 7K_round3_stylistic_v_rest
  - 10K_round3_stylistic_v_rest